import jsPDF from 'jspdf';
import { Achievement } from '../types';

export const generatePDF = (studentData: any, achievements: Achievement[]) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(59, 130, 246); // blue-600
  doc.text('MyWork Portfolio', 20, 30);
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(studentData.name, 20, 50);
  
  doc.setFontSize(12);
  doc.text(`${studentData.rollNumber} | ${studentData.department}`, 20, 60);
  doc.text(`Year ${studentData.year}, Section ${studentData.section}`, 20, 70);
  doc.text(`CGPA: ${studentData.cgpa} | ${studentData.email}`, 20, 80);
  
  // Achievements
  doc.setFontSize(16);
  doc.setTextColor(59, 130, 246);
  doc.text('Verified Achievements', 20, 100);
  
  let yPosition = 120;
  
  achievements.forEach((achievement, index) => {
    if (yPosition > 260) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`${index + 1}. ${achievement.title}`, 20, yPosition);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`${achievement.organization} | ${achievement.date.toLocaleDateString('en-IN')}`, 30, yPosition + 10);
    doc.text(achievement.description, 30, yPosition + 20);
    
    yPosition += 35;
  });
  
  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by MyWork - Campus Achievement Management Platform', 20, 280);
    doc.text(`Page ${i} of ${pageCount}`, 150, 280);
  }
  
  doc.save(`${studentData.name.replace(/\s+/g, '_')}_Portfolio.pdf`);
};